# Generated by Django 3.0.5 on 2021-02-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210213_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.FloatField(default=1613329355.279885),
        ),
    ]
