# Generated by Django 3.0.5 on 2021-02-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.FloatField(default='', max_length=50)),
                ('stockSymbol', models.CharField(default='', max_length=50)),
                ('userId', models.CharField(default='', max_length=50)),
                ('timestamp', models.FloatField(default='', max_length=50)),
                ('cryptokey', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
