version: '2'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  quote_server:
    container_name: quote_server
    build: ./quote_server
    command: python quoteServer.py 0.0.0.0:4444
    volumes:
      - ./quote_server:/code
    ports:
      - "4444:4444"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  server:
    container_name: transaction_server
    build: ./transaction_server
    command: gunicorn manage.py transaction_server.wsgi 0.0.0.0:8000
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8001:8000"
      - "4445:4444"
    depends_on:
      - mongodb
      - quote_server
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=quote_server
      - serverNum=1
  
  server2:
    container_name: transaction_server2
    build: ./transaction_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8002:8000"
      - "4446:4444"
    depends_on:
      - mongodb
      - quote_server
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=quote_server
      - serverNum=2

  server3:
    container_name: transaction_server3
    build: ./transaction_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8003:8000"
      - "4447:4444"
    depends_on:
      - mongodb
      - quote_server
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=quote_server
      - serverNum=3
  
  server4:
    container_name: transaction_server4
    build: ./transaction_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8004:8000"
      - "4448:4444"
    depends_on:
      - mongodb
      - quote_server
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=quote_server
      - serverNum=4

  server5:
    container_name: transaction_server5
    build: ./transaction_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8005:8000"
      - "4449:4444"
    depends_on:
      - mongodb
      - quote_server
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=quote_server
      - serverNum=5

  nginx:
    container_name: nginx
    build: ./transaction_server/nginx
    ports:
      - "8080:80"
    depends_on:
    - server
    - server2
    - server3
    - server4
    - server5

