version: '2'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  server:
    container_name: transaction_server
    build: ./transaction_server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8000:8000"
      - "4444:4444"
    depends_on:
      - mongodb
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2