version: '2'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command: --quiet

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  server:
    container_name: transaction_server
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8001:8000"
      - "4445:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=1

  server2:
    container_name: transaction_server2
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8002:8000"
      - "4446:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=2
 
  server3:
    container_name: transaction_server3
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8003:8000"
      - "4447:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=3

  server4:
    container_name: transaction_server4
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8004:8000"
      - "4448:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=4

  server5:
    container_name: transaction_server5
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8005:8000"
      - "4449:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=5

  server6:
    container_name: transaction_server6
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8006:8000"
      - "4450:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=6

  server7:
    container_name: transaction_server7
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8007:8000"
      - "4451:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=7
 
  server8:
    container_name: transaction_server8
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8008:8000"
      - "4452:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=8

  server9:
    container_name: transaction_server9
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8009:8000"
      - "4453:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=9

  server10:
    container_name: transaction_server10
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8010:8000"
      - "4454:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=10

  server11:
    container_name: transaction_server11
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8011:8000"
      - "4455:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=11

  server12:
    container_name: transaction_server12
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8012:8000"
      - "4456:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=12
 
  server13:
    container_name: transaction_server13
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8013:8000"
      - "4457:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=13

  server14:
    container_name: transaction_server14
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8014:8000"
      - "4458:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=14

  server15:
    container_name: transaction_server15
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8015:8000"
      - "4459:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=15

  server16:
    container_name: transaction_server16
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8016:8000"
      - "4460:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=16

  server17:
    container_name: transaction_server17
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8017:8000"
      - "4461:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=17
 
  server18:
    container_name: transaction_server18
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8018:8000"
      - "4462:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=18

  server19:
    container_name: transaction_server19
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8019:8000"
      - "4463:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=19

  server20:
    container_name: transaction_server20
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8020:8000"
      - "4464:4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=20

  nginx:
    build: ./transaction_server/nginx
    ports: 
      - "8080:80"
    depends_on:
    - server
    - server2
    - server3
    - server4
    - server5
    - server6
    - server7
    - server8
    - server9
    - server10
    - server11
    - server12
    - server13
    - server14
    - server15
    - server16
    - server17
    - server18
    - server19
    - server20
