version: '2'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  quote_server:
    container_name: quote_server
    build: ./quote_server
    command: python quoteServer.py 0.0.0.0:4444
    volumes:
      - ./quote_server:/code
    ports:
      - "4444:4444"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  server:
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8000"
      - "4444"
    depends_on:
      - mongodb
      - quote_server
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=quote_server
      - serverNum=1
  
  nginx:
    container_name: nginx
    build: ./transaction_server/nginx
    ports:
      - "8080:80"
    depends_on:
      - server

  web_server:
    container_name: web_server
    build: ./react_web_server
    volumes:
      - './react_web_server:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    depends_on:
      - nginx

