version: '2'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command: --quiet
    networks: 
      - localnet

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    networks: 
      - localnet

  server:
    build: ./transaction_server
    command: gunicorn server.wsgi:application
    volumes:
      - ./transaction_server/src:/code
    ports:
      - "8000"
      - "4444"
    depends_on:
      - mongodb
      - redis
    entrypoint: /entrypoint.sh
    environment: 
      - quoteServerHost=192.168.4.2
      - serverNum=1
    networks: 
      - localnet

  nginx:
    build: ./transaction_server/nginx
    ports: 
      - "8080:80"
    depends_on:
    - server
    networks: 
      - localnet

  web_server:
    container_name: web_server
    build: ./react_web_server
    volumes:
      - './react_web_server:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    depends_on:
      - nginx

networks:
  localnet:
    driver: 'bridge'
