# Generated by Django 3.0.5 on 2021-02-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('stockSymbol', models.CharField(max_length=50)),
                ('triggerPoint', models.FloatField(blank=True)),
                ('shares', models.IntegerField()),
                ('isBuy', models.BooleanField()),
            ],
        ),
    ]
