# Generated by Django 3.0.5 on 2021-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggers', '0002_trigger_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='triggerPoint',
            field=models.FloatField(blank=True),
        ),
    ]
