# Generated by Django 3.1.6 on 2021-02-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='userId',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
