# Generated by Django 3.0.5 on 2021-02-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='reserved',
        ),
    ]
