# Generated by Django 3.0.5 on 2021-02-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50)),
                ('userId', models.CharField(blank=True, max_length=50)),
                ('stockSymbol', models.CharField(blank=True, max_length=50)),
                ('userCommand', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('quoteServerTime', models.BigIntegerField(default=0)),
                ('cryptoKey', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField(blank=True)),
                ('server', models.CharField(blank=True, max_length=50)),
                ('transactionNum', models.IntegerField(blank=True)),
                ('amount', models.FloatField(blank=True)),
                ('systemEvent', models.CharField(blank=True, max_length=50)),
                ('debugEvent', models.CharField(blank=True, max_length=50)),
                ('errorEvent', models.CharField(blank=True, max_length=50)),
                ('debugMessage', models.CharField(blank=True, max_length=50)),
                ('fileName', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
