# Generated by Django 3.0.5 on 2021-02-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210217_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.FloatField(default=1613603615.8773472),
        ),
    ]
